image: maven:3.3.9-jdk-8
variables:
  MAVEN_OPTS: -Dmaven.repo.local=/cache/repository/maven
stages:
  - build
  - deploy
# jobs
build:
  stage: build
  script:
    - mvn clean package --settings .maven-settings.xml
  artifacts:
    paths:
    - modules/plugin/target/AmpItems.jar
deploy:
  stage: deploy
  script:
    - mvn clean deploy --settings .maven-settings.xml
  only:
    - master
